name: Website Product Monitor

on:
  workflow_dispatch:
  schedule:
    - cron: '8 * * * *'

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers
        run: python -m playwright install

      #- name: Run Mammut script
        #run: python Mammut.py

      - name: Run Arc'teryx Sporting Life script
        run: python arcteryx-sportinglife.py
      
      - name: Run Arc'teryx Official script
        run: python arcteryx-offical.py

      - name: Commit and push if there are changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git diff --staged --quiet || git commit -m "Automated update of product data"
          git push
